---
fixtures:
  repositories:
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    network: "git://github.com/simp/pupmod-simp-network"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    stdlib:
      repo: "git://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
  symlinks:
    gfs2: "#{source_dir}"
