---
fixtures:
  repositories:
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    network: "https://github.com/simp/pupmod-simp-network"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
  symlinks:
    gfs2: "#{source_dir}"
